---
:typeraker:
  :build_dir: build
  :graphics_dir: src/figures

:template:
  :klass:
    :uiothesis:
      - 11pt
  :packages:
    - :graphicx:
    - :longtable:
    - :lscape:
    - :caption:
    - :natbib:
    - :paralist:
    - :ragged2e:
  :title:
    Social Navigation in Modern Web Sites
  :sub_title:
    Classification, Prototyping, and Applicability
  :author:
    :name:
      Eivind Uggedal
  :scm: Mercurial
  :table_of_contents: true
  :list_of_figures: true
  :list_of_tables: true
  :main_content:
    - introduction
    - background
    - methodology
    - analysis
    - discussion
    - conclusion
  :appendices:
    - content.inventory
  :bibliography:
    :bibliography:
      :apalike
